### ISSUE TITLE
an error occoured while creating the pipeline | DLL_THREAD_ATTACH

### ISSUE THREAD

**Issue by royharoush** [fdiskyou/PowerOPS#1]
Hi,
after compiling without errors, i get the following error on execution. 

![2016-08-17 15_52_23-roy](https://cloud.githubusercontent.com/assets/8113056/17736893/caa4014c-6492-11e6-9cdd-302d4cf55592.png)

any idea what could cause this or how to fix it ? 
Thanks !
Roy

**Comment by fdiskyou** [comment]
Which Windows version are you using? Which arch?

**Comment by royharoush** [comment]
Win10 64bit.

**Comment by fdiskyou** [comment]
Ok, I can reproduce the problem. It seems Microsoft blocks access to the Amsi.dll (to bypass windows defender). My guess is if you execute powerops, then delete the Amsi.dll it will work however Windows Defender will flag mimikatz as malicious. If you delete Amsi.dll and disable Windows Defender I guess everything works, right? I'll have to do a bit of research on this again.

**Comment by fdiskyou** [comment]
I just committed a fix. Can you please update and test? Thank you.

**Comment by royharoush** [comment]
looks like it's fixed , Thanks !
